### ISSUE TITLE
No trained model available.

### ISSUE THREAD

**Issue by j-a-dietrich** [zhanghailiangcsu/MSBERT#1]
Hello,

maybe I am missing something, but I cannot see from where to get the trained model that was used in the paper. 

Best,
Jonas

**Comment by zhanghailiangcsu** [comment]
We upload the trained MSBERT model to release. It can be accessed at https://github.com/zhanghailiangcsu/MSBERT/releases/tag/1.0. You can also retrain MSBERT on your data
